config/routes.rb
Rails.application.routes.draw do
  resources :buy_requests do
    post 'submit', action: :submit
    post 'is_sold', action: :is_sold
    get 'lock_buy', action: :lock_buy
    post 'audit', action: :audit



    post 'audit_reject', action: :audit_reject
    get 'reject_buy', action: :reject_buy
  end
  resources :sell_requests do
    post 'resubmit', action: :resubmit
    post 'upload_invoice', action: :upload_invoice
  end
  get 'dashboard/home', action: :home, controller: 'dashboard'
  get 'dashboard/sell', action: :sell, controller: 'dashboard'
  get 'dashboard/buy', action: :buy, controller: 'dashboard'
  get 'dashboard/business_config', action: :business_config, controller: 'dashboard'
  get 'dashboard/select_scrips_user', action: :select_scrips_user, controller: 'dashboard'
  get 'dashboard/select_scrips_ops', action: :select_scrips_ops, controller: 'dashboard'

  get 'dashboard/download_pdf', action: :download_pdf, controller: 'dashboard'


  get 'dashboard/verify_buy', action: :verify_buy, controller: 'dashboard'
  get 'dashboard/audit_dashboard', action: :audit_dashboard, controller: 'dashboard'
  get 'dashboard/procees_to_sell', action: :procees_to_sell, controller: 'dashboard'


  resources :permissions, only: [:index, :edit, :update]

  resources :buy_sell_binding, only: [:create, :destroy]

  get 'verify_sell_rejections', action: :rejections, controller: 'verify_sell'

  resources :verify_sell, only: [:index, :show] do
    post 'verify', action: :verify
    post 'reject', action: :reject
    get 'request_lock', action: :request_lock

  end
  get 'dashboard/invoices', action: :invoices, controller: 'dashboard'

  get 'dashboard/buy_request_audit', action: :buy_request_audit, controller: 'dashboard'

  resources :kyc_documents do
    post 'pan', action: :pan
    post 'null_cheque', action: :null_cheque
    post 'incorporation_cert', action: :incorporation_cert
    post 'phonenumber', action: :phonenumber
    post 'approval', action: :approval
    post 'reject', action: :reject
    post 'information', action: :information
    get 'oops_lock', action: :oops_lock
  end
  resources :s3url, only: [:index]
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", confirmations: 'confirmations' }
  root to: "home#index"
  get 'kyc', action: :show, controller: 'kyc', as: 'kyc'
  get 'logout', action: :logout, controller: 'application', as: 'logout'
  resources :business_configs, only: [ :update ]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :setup
  layout "application"

  def setup
    @hide_side_bar = false
    @user = current_user 
    @side_menu = []
    {
      "sell" => [{name: "Place Sell Request", target: new_sell_request_path}],
      "buy" => [{name: "Place Buy Request", target: new_buy_request_path}]
    }.each do |k,v|
      if current_user.can?(k)
        v.each { |button| @side_menu.push(button) }
      end
    end
    @side_menu.push({name: "Invoices", target: dashboard_home_path})
    @side_menu.push({name: "Logout", target: logout_path})
  end

  def home
    @dashboard_home_buttons = []
    if current_user.can?("sell")
      @dashboard_home_buttons.push({src: "https://scripmarket-public.s3.ap-south-1.amazonaws.com/sell_button.png",
                                url: dashboard_sell_path})
    end
    if current_user.can?("buy")
      @dashboard_home_buttons.push({src: "https://scripmarket-public.s3.ap-south-1.amazonaws.com/buy_button.png",
                                url: dashboard_buy_path})
    end
    if current_user.can?("user_admin") or current_user.is_super_admin?
      @dashboard_home_buttons.push({src: "https://scripmarket-public.s3.ap-south-1.amazonaws.com/permissions_button.png",
                                url: permissions_path})
    end
    if current_user.can?("verify_scrip")
      @dashboard_home_buttons.push({src: "https://scripmarket-public.s3.ap-south-1.amazonaws.com/verify_sell.png",
                                url: verify_sell_index_path})
    end
    if current_user.can?("verify_kyc") and current_user.role == "ops"
      @dashboard_home_buttons.push({src: "https://scripmarket-public.s3.ap-south-1.amazonaws.com/verify_kyc.png",
      url: kyc_documents_path})
    end
    if current_user.is_super_admin?
      @dashboard_home_buttons.push({src: "https://scripmarket-public.s3.ap-south-1.amazonaws.com/business_config.png",
      url: dashboard_business_config_path})
    end

    if current_user.can?("verify_buy") and current_user.role == "ops"
      @dashboard_home_buttons.push({src: "https://scripmarket-public.s3.ap-south-1.amazonaws.com/verify_buy_button.png",
      url: dashboard_verify_buy_path})
    end
    @current_user_id = current_user.id
    @current_user_email = current_user.email
    @current_user_name =  current_user.kyc_documents.last[:name]
    @current_user_role = current_user.role
    @total_sell_request_count =   current_user.is_super_admin? ? SellRequest.all.count  : SellRequest.where("user_id = ?",@current_user_id).count
    @total_sell_verified_request_count = current_user.is_super_admin? ? SellRequest.where("verified = true").count : SellRequest.where("user_id = ? AND verified = true",@current_user_id).count
   

    @total_sell_un_verified_request_count = current_user.is_super_admin? ? SellRequest.where("verified = false").count : SellRequest.where("user_id = ? AND verified = false",@current_user_id).count
   
    @total_buy_request_count = current_user.is_super_admin? ? BuyRequest.all.count : BuyRequest.where("user_id = ?",@current_user_id).count
   
    if current_user.is_super_admin? 
      @total_buy_request_verified_sold_count = BuyRequest.where("sold = true").count
     
      sell_request = SellRequest.where("verified = true AND deleted = false")
     
      @sell_request_sold = SellRequest.where(" verified = true AND sold = true AND deleted = false",).count


    else
      @total_buy_request_verified_sold_count = BuyRequest.where("user_id = ? AND sold = true",@current_user_id).count
     
      sell_request = SellRequest.where("user_id = :user_id AND verified = true AND deleted = false", {user_id: @current_user_id})
     
      @sell_request_sold = SellRequest.where("user_id = :user_id AND verified = true AND sold = true AND deleted = false", {user_id: @current_user_id}).count
    end
    @total_savings = 0
    sell_request.each do |sale|
    @total_savings +=  ((sale.rate.to_d/10000) - (sale.commission.to_d/10000))*(sale.scrip_value.to_d/100)
    end
    @buy_request = current_user.is_super_admin? ? BuyRequest.all : BuyRequest.where("user_id = ?",@current_user_id)
    @selected_sell_details = []
    @available_sell_details = []
    @selected_total_value = 0
    @selected_total_sale_price = 0
    @total_earnings = 0
    @selected_sale_price = 0
    @buy_request.each do |br|
      br.sell_requests.each do |sell_request|
        binding = BuySellBinding.find_by(sell_request_id: sell_request.id, buy_request_id: br.id)
        sale = { :sale => sell_request,
                  :binding => binding }
        @selected_sell_details.append(sale)
        @selected_total_value += sell_request.scrip_value.to_d
        total_sale_rate = sell_request.rate.to_d + binding.buy_commission.to_d
        @selected_sale_price += (sell_request.scrip_value.to_d*total_sale_rate/100)
        @selected_total_sale_price += (sell_request.scrip_value.to_d - (@selected_sale_price))
      end
    end  
    @total_earnings = @selected_total_value/100 - @selected_sale_price/10000
  end

  def buy
    if !current_user.can?("buy")
      render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
      return 
    end
    @active_buys = BuyRequest.active_buys(current_user)
    @completed_buys = BuyRequest.completed_buys(current_user)
  end

  def sell
    if !current_user.can?("sell")
      render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
      return 
    end
    @active_sales = SellRequest.active_sales(current_user.id)
    @unverified_sales = SellRequest.unverified_sales(current_user.id)
    @completed_sales = SellRequest.completed_sales(current_user.id)
    @current_user = current_user
  end

  def business_config

    if !["pramodbha8@gmail.com"].split(',').flatten.include?(current_user.email)
      render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
      return
    end 
    @business_config = BusinessConfig.get_latest(current_user.id)
  end

  def select_scrips_user
    if !current_user.can?("buy")
      render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
      return 
    end

    buy_id = params["buy_id"]
    @buy_request = BuyRequest.find(buy_id)
    if @buy_request == nil
      flash[:alert] = "Could not find Buy Request"
      redirect_to :dashboard_path
      return
    end

    # if @buy_request.user.id != current_user.id 
    #   render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
    #   return 
    # end

    @selected_sell_details = []
    @available_sell_details = []
    @selected_total_value = 0
    @selected_total_sale_price = 0
    sell_ids = {}
    @selected_sale_price = 0
    @buy_request.sell_requests.each do |sell_request|
      binding = BuySellBinding.find_by(sell_request_id: sell_request.id, buy_request_id: @buy_request.id)
      sale = { :sale => sell_request,
                :binding => binding }
      @selected_sell_details.append(sale)
      @selected_total_value += sell_request.scrip_value.to_d
      total_sale_rate = sell_request.rate.to_d + binding.buy_commission.to_d
      @selected_sale_price += (sell_request.scrip_value.to_d*total_sale_rate/100)
      @selected_total_sale_price += (sell_request.scrip_value.to_d - (@selected_sale_price))
      sell_ids[sell_request.id] = true
    end

    SellRequest.active_sales_all.each do |sell_request|
      if !sell_ids.key?(sell_request.id)
        sale = { :sale => sell_request,
        :binding => nil }
        @available_sell_details.append(sale)
      end
    end

    @business_config = BusinessConfig.get_latest(current_user.id)
  end

  def verify_buy
    allowed = current_user.can?("verify_buy")
    allowed = allowed and current_user.role == "ops"

    if !allowed 
      render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
      return 
    end

    @active_buys = BuyRequest.active_buys_submitted
  end

  def audit_dashboard
    @open_audit = BuyRequest.open_audit(current_user)
    @accepted_audit = BuyRequest.accepted_audit(current_user)
    @rejected_audit = BuyRequest.rejected_audit(current_user)
    
  end

  def procees_to_sell
  end

  def select_scrips_ops
    allowed = current_user.can?("verify_buy")
    allowed = allowed and current_user.role == "ops"

    if !allowed 
      render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
      return 
    end

    buy_id = params["buy_id"]
    @buy_request = BuyRequest.find(buy_id)
    if @buy_request == nil
      flash[:alert] = "Could not find Buy Request"
      redirect_to :dashboard_path
      return
    end

    @buy_phonenumber = ""
    @buy_name = ""
    @buy_request.user.kyc_documents.select do |kyc_document|
      @buy_name = kyc_document.name
      @buy_phonenumber = kyc_document.phonenumber
    end
 
    @selected_sell_details = []
    @available_sell_details = []
    @selected_total_value = 0
    @selected_total_sale_price = 0
    @selected_sale_price = 0
    sell_ids = {}
    @buy_request.sell_requests.each do |sell_request|
      binding = BuySellBinding.find_by(sell_request_id: sell_request.id, buy_request_id: @buy_request.id)
      phonenumber = ""
      name = ""
      sell_request.user.kyc_documents.select do |kyc_document|
        if kyc_document.status.eql?("APPROVED") || kyc_document.status.eql?("SUBMITTED")
          name = kyc_document.name
          phonenumber = kyc_document.phonenumber
        end
      end

      sale = { :sale => sell_request,
                :binding => binding,
                :name => name,
                :phonenumber => phonenumber }

      @selected_sell_details.append(sale)
      @selected_total_value += sell_request.scrip_value.to_d
      total_sale_rate = sell_request.rate.to_d + binding.buy_commission.to_d

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/business_config.html.erb
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
 <h2 class="title">Business Configuration</h2> 
</nav>
<%= form_with(url: business_config_path(@business_config), method: "patch",data: { confirm: "return confirm('Do you really want to update config?"}) do %>
    <%= hidden_field_tag "referrer", dashboard_business_config_path -%>
      <div class="form-inline">
        <div class="form-group" style="margin-left: 255px;">
          Configuration&nbsp;&nbsp;<%= text_area_tag "config", @business_config.config.to_json, class: "form-control m-t-5", autocomplete: "off" ,style: "width: 450px;"-%>
        </div>
      </div>

    <%= submit_tag("Submit", :class => "btn btn-info m-t-5",:style => "    margin-left: 408px;margin-top: 30px;") -%>
    <%= link_to "Back", dashboard_home_path,:class => "btn btn-info index-link" %>

  <% end -%>
<style type="text/css">
  .index-link {
    text-transform: capitalize;
    margin-top: 30px;
  }
</style>

app/views/dashboard/select_scrips_user.html.erb
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
 <h2 class="title">Select Script</h2> 
</nav>
<table class="styled-table" style="margin-left: 102px;margin-top: 10px;">
    <thead>
      <tr>
        <th scope="col">Sl No</th>
        <th scope="col">Date Of Sale</th>
        <th scope="col">Scrip Amount Requested(Rs)</th>
        <th scope="col">Scrip Amount Selected(Rs)</th>
        <th scope="col">Scrip Sale Price(Rs)</th>
        <th scope="col">Total Amount Saved(Rs)</th>
        <% if @buy_request.sold == false %> 
          <th scope="col">Actions</th>
        <% else %>  
          <th scope="col">Audited</th>
        <% end %>  
       
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">1</th>
        <td><%= @buy_request.buy_date.strftime('%d/%m/%Y') %></td>
        <td><%= @buy_request.scrip_value.to_d/100 %></td>
        <td><%= %><%= @selected_total_value/100 %></td>
        <td><%= %><%= (@selected_sale_price/10000).round(2) %></td>
        <td><%= %><%= (@selected_total_value/100 - @selected_sale_price/10000).round(2) %></td>
        <% if @buy_request.sold == false %>
          <td class="row">
            <%= form_with(url: buy_request_path(@buy_request),local: true,   :html => { :onsubmit => "return confirm('Do you really want to delete this?');" }, :method => "delete",) do %>
              <%= hidden_field_tag "referrer", dashboard_buy_path -%>
              <%= button_tag(type: "submit", class: "btn") do %>
                <i class="fa fa-trash" title="delete"></i>
              <% end %>
            <% end -%>
            <%= link_to ('<i class="fa fa-pencil-square-o" title="edit"></i>').html_safe,edit_buy_request_path(@buy_request) %>
          </td>
        <% else %>
          
        <td><%= %><%= @buy_request.is_auidted %></td>
        <% end %>

      </tr>
    </tbody>
</table>
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
 <h2 class="title" style="padding-left: 365px">Selected Scrip</h2> 
</nav>

<table class="styled-table" style="margin-left: 100px;">
    <thead>
    <tr>
      <th scope="col">Sl No</th>
      <th scope="col">Scrip Number</th>
      <th scope="col">Seller Name</th>
      <th scope="col">Seller Phonenumber</th>

      <th scope="col">Scrip Date</th>
      <th scope="col">Scrip Value (Rs)</th>
      <th scope="col">Sale Rate ('%')</th>
      <th scope="col">Sale Price (Rs)</th>
      <th scope="col">Sold</th>
      <% if @buy_request.sold == false  &&  @buy_request.submitted != true%>
        <th scope="col">Actions</th>
      <% end %>  
    </tr>
    </thead>
    <tbody>
      <% if @selected_sell_details.present? %>
        <% @selected_sell_details.each_with_index do |sale_detail, index| %>
          <tr>
            <td scope="row"><%= index+1 %></th>
            <td class="trigger"><%= link_to "#{sale_detail[:sale].scrip_number}", verify_sell_path(sale_detail[:sale]) , target: :_blank%> </td>
            <td class="trigger"> <%= sale_detail[:sale]&.user&.kyc_documents.first.name  %></td>
            <td class="trigger"> <%= sale_detail[:sale]&.user&.kyc_documents.first.phonenumber %></td>

            <td><%= sale_detail[:sale].scrip_date %></td>
            <td><%= sale_detail[:sale].scrip_value/100 %></td>
            <td><%= ((sale_detail[:sale].rate.to_d + sale_detail[:binding].buy_commission.to_d)/100).round(2) %></td>
            <td><%= (((sale_detail[:sale].rate.to_d + sale_detail[:binding].buy_commission.to_d)/10000)*(sale_detail[:sale].scrip_value.to_d/100)).round(2) %></td>
                <% if sale_detail[:sale].sold == true %>
                  <td>Yes</td>
                <% else %>
                  <td>No</td>                        
                <% end %>
            <% if @buy_request.sold == false && @buy_request.submitted != true %>
              <td><%= form_with(url: buy_sell_binding_path(sale_detail[:binding]),local: true,  :html => { :onsubmit => "return confirm('Do you really want to deselect this?');" }, method: "delete") do -%>
                <%= hidden_field_tag "referrer", dashboard_select_scrips_user_path(buy_id:@buy_request.id) -%>
                <%= submit_tag("Deselect", :class => "btn btn-info") -%>
              <% end -%></td>
            <% end %>  
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td colspan="15" style="text-align: center; "><b>There is Selected Sales </b></td>
        </tr>  
      <% end -%>

    </tbody>
</table>


<% if @buy_request.sold == false && @buy_request.submitted != true %>
  <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
    <h2 class="title" style="padding-left: 365px">Available Scrip</h2> 
  </nav>
  <table class="styled-table" style="margin-left: 100px;">
    <thead>
    <tr>
      <th scope="col">Sl No</th>
      <th scope="col">Scrip Number</th>
      <th scope="col">Seller Name</th>
      <th scope="col">Seller Phonenumber</th>

      <th scope="col">Scrip Date</th>
      <th scope="col">Scrip Value (Rs)</th>
      <th scope="col">Sale Rate ('%')</th>
      <th scope="col">Sale Price (Rs)</th>
      <th scope="col">Sold</th>
      <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
      <% if @available_sell_details.present? %>
        <% @available_sell_details.each_with_index do |sale_detail, index| %>
          <tr>
            <th scope="row"><%= index+1 %></th>
            <td class="trigger"><%= link_to "#{sale_detail[:sale].scrip_number}", verify_sell_path(sale_detail[:sale]) , target: :_blank%> </td>
            <td class="trigger"> <%= sale_detail[:sale]&.user&.kyc_documents.first.name  %></td>
            <td class="trigger"> <%= sale_detail[:sale]&.user&.kyc_documents.first.phonenumber %></td>

            <td><%= sale_detail[:sale].scrip_date %></td>
            <td><%= sale_detail[:sale].scrip_value/100 %></td>
            <td><%= ((sale_detail[:sale].rate.to_d + @business_config.config["buy_commission"].to_d)/100).round(2) %></td>
            <td><%= (((sale_detail[:sale].rate.to_d + @business_config.config["buy_commission"].to_d)/10000)*(sale_detail[:sale].scrip_value.to_d/100)).round(2) %></td>
                <% if sale_detail[:sale].sold == true %>
                  <td>Yes</td>
                <% else %>
                  <td>No</td>                        
                <% end %>

            <td><%= form_with(url: buy_sell_binding_index_path, method: "post", :html => { :onsubmit => "return confirm('Do you really want to select this?');" }) do %>
              <%= hidden_field_tag "referrer", dashboard_select_scrips_user_path(buy_id:@buy_request.id)  -%>
              <%= hidden_field_tag "buy_request_id", @buy_request.id -%>
              <%= hidden_field_tag "sell_request_id", sale_detail[:sale].id -%>
              <%= submit_tag("Select", :class => "btn btn-primary") -%>
            <% end -%></td>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td colspan="15" style="text-align: center; "><b>There is Available Sales </b></td>
        </tr>
      <% end -%>

    </tbody>
  </table>
  <% if  @buy_request.submitted != true %>
    <%= form_with(url: buy_request_submit_path(@buy_request), method: "post", :html => { :onsubmit => "return confirm('Do you really want to submit this?');" }) do %>
      <%= hidden_field_tag "referrer", dashboard_buy_path -%>
      <%= submit_tag("Submit", :class => "btn btn-info",:style =>"margin-left: 395px") -%>
      <%= link_to "Back", dashboard_buy_path,:class => "btn btn-info index-link" ,:style =>"    margin-top: 2px;
    height: 34px;
    margin-left: 10px;"%>
    <% end -%>
  <% end %>
  
<% end %>
<% if  @buy_request.submitted == true %>
      <%= link_to "Back", dashboard_buy_path,:class => "btn btn-info index-link",:style =>"    margin-left: 429px;" %>
<% end %>

    <% if @user.is_super_admin?  %>
<% if @buy_request.is_auidted != true && @buy_request.sold == true%>
  <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
    <h2 class="title" style="padding-left: 365px">Audit Actions</h2> 
  </nav>


    <div class="kyc-document-div">
        <div class="button-div">
            <%= form_with(url: buy_request_audit_path(@buy_request), method: "post", :html => { :onsubmit => "return confirm('Do you really want approve Buy Request?');" } ) do %>
                <%= submit_tag("Audit Approve", :class => "btn btn-success",:style =>"    margin-left: 298px;") %>
            <% end %>



        </div>

        <div class="button-div ">
            <%= form_with(url: buy_request_audit_reject_path(@buy_request), method: "post", :html => { :onsubmit => "return confirm('Do you really want audit reject ?');" } ) do %>
                <%= text_area_tag :message, nil, placeholder: "Rejection Reason" ,style:"    margin-top: -75px;
    margin-left: 440px;
}"%>
                <%= submit_tag("Audit Reject", :class => "btn btn-danger",:style => "    margin-top: -72px;
    width: 104px;
    margin-left: 600px;") %>
            <% end %>

            </form>
        </div>
    </div>
  <% else %>

 <% end %>   

 <% end %>   


<style type="text/css">
.styled-table {
    border-collapse: collapse;
    margin: 25px 0;
    font-size: 0.9em;
    font-family: sans-serif;
    min-width: 700px;
    box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
    margin-left: 64px;
}
.styled-table thead tr {
    background-color: #009879;
    color: #ffffff;
    text-align: left;
}
.styled-table th,
.styled-table td {
    padding: 12px 15px;
}
.styled-table tbody tr {
    border-bottom: 1px solid #dddddd;
}

.styled-table tbody tr:nth-of-type(even) {
    background-color: #f3f3f3;
}

.styled-table tbody tr:last-of-type {
    border-bottom: 2px solid #009879;
}
.styled-table tbody tr.active-row {
    font-weight: bold;
    color: #009879;
}
  .index-link {
    text-transform: capitalize;
  }
#wrapper #content-wrapper {
    background-color: #f8f9fc;
    width: 100%;
  }
</style>