config/routes.rb
Rails.application.routes.draw do
  resources :buy_requests do
    post 'submit', action: :submit
    post 'is_sold', action: :is_sold
    get 'lock_buy', action: :lock_buy
    post 'audit', action: :audit



    post 'audit_reject', action: :audit_reject
    get 'reject_buy', action: :reject_buy
  end
  resources :sell_requests do
    post 'resubmit', action: :resubmit
    post 'upload_invoice', action: :upload_invoice
  end
  get 'dashboard/home', action: :home, controller: 'dashboard'
  get 'dashboard/sell', action: :sell, controller: 'dashboard'
  get 'dashboard/buy', action: :buy, controller: 'dashboard'
  get 'dashboard/business_config', action: :business_config, controller: 'dashboard'
  get 'dashboard/select_scrips_user', action: :select_scrips_user, controller: 'dashboard'
  get 'dashboard/select_scrips_ops', action: :select_scrips_ops, controller: 'dashboard'

  get 'dashboard/download_pdf', action: :download_pdf, controller: 'dashboard'


  get 'dashboard/verify_buy', action: :verify_buy, controller: 'dashboard'
  get 'dashboard/audit_dashboard', action: :audit_dashboard, controller: 'dashboard'
  get 'dashboard/procees_to_sell', action: :procees_to_sell, controller: 'dashboard'


  resources :permissions, only: [:index, :edit, :update]

  resources :buy_sell_binding, only: [:create, :destroy]

  get 'verify_sell_rejections', action: :rejections, controller: 'verify_sell'

  resources :verify_sell, only: [:index, :show] do
    post 'verify', action: :verify
    post 'reject', action: :reject
    get 'request_lock', action: :request_lock

  end
  get 'dashboard/invoices', action: :invoices, controller: 'dashboard'

  get 'dashboard/buy_request_audit', action: :buy_request_audit, controller: 'dashboard'

  resources :kyc_documents do
    post 'pan', action: :pan
    post 'null_cheque', action: :null_cheque
    post 'incorporation_cert', action: :incorporation_cert
    post 'phonenumber', action: :phonenumber
    post 'approval', action: :approval
    post 'reject', action: :reject
    post 'information', action: :information
    get 'oops_lock', action: :oops_lock
  end
  resources :s3url, only: [:index]
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", confirmations: 'confirmations' }
  root to: "home#index"
  get 'kyc', action: :show, controller: 'kyc', as: 'kyc'
  get 'logout', action: :logout, controller: 'application', as: 'logout'
  resources :business_configs, only: [ :update ]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/kyc_document.rb
class KycDocument < ApplicationRecord
  belongs_to :user
  # removed approved_by because it caused approved_by to not be nullable
  belongs_to :approved_by, :class_name => 'User', optional: true


end

app/controllers/kyc_documents_controller.rb
class KycDocumentsController < ApplicationController
  before_action :authenticate_user!
  before_action :setup
  before_action :set_kyc_document, only: [:show, :edit, :destroy, :update]
  before_action :set_parent_kyc_document, only: [:pan, :null_cheque, :incorporation_cert,
                                                 :phonenumber, :approval, :reject,
                                                 :information,:state,:gst_number,:pan_card_number,:kyc_pan_card_number,:iec_number]

  layout "application"


  def setup
    @user = current_user
    @hide_side_bar = !current_user.kyc_approved 
    @unknown_image = 'https://scripmarket-public.s3.ap-south-1.amazonaws.com/unknown_image.png'
    @valid_email = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  end

  # GET /kyc_documents
  # GET /kyc_documents.json
  def index
    @kyc_documents = KycDocument.includes(:user).includes(:approved_by).all
  end

  # GET /kyc_documents/1
  # GET /kyc_documents/1.json
  def show
    @pan_url = pan_url
    @null_cheque_url = null_cheque_url
    @incorporation_cert_url = incorporation_cert_url
  end

  def presigned_url (bucket, key)
    signer = Aws::S3::Presigner.new
    url = signer.presigned_url(:get_object, bucket: bucket, key: key)
  end

  def pan_url()
    return @unknown_image unless (@kyc_document.pan_card and @kyc_document.pan_card.length)
    presigned_url('scripmarket-kyc', @kyc_document.pan_card)
  end

  def null_cheque_url()
    return @unknown_image unless (@kyc_document.null_cheque and @kyc_document.null_cheque.length)
    presigned_url('scripmarket-kyc', @kyc_document.null_cheque)
  end

  def incorporation_cert_url()
    return @unknown_image unless (@kyc_document.incorporation_cert and @kyc_document.incorporation_cert.length)
    presigned_url('scripmarket-kyc', @kyc_document.incorporation_cert)
  end

  # GET /kyc_documents/new
  def new
    open_documents = KycDocument.where("user_id = ? and (status != ?)", current_user.id, 'INVALID')
    if open_documents.length > 0
      @kyc_document = open_documents.last 
    else
      @kyc_document = KycDocument.create(user_id: current_user.id, status: "DRAFT")
    end
    @pan_url = pan_url
    @null_cheque_url = null_cheque_url
    @incorporation_cert_url = incorporation_cert_url

  end

  # GET /kyc_documents/1/edit
  def edit
    @kyc_document.pan_card = kyc_document_params
  end

  # POST /kyc_documents/1/pan
  def pan
    @kyc_document.pan_card = params[:key]
    @kyc_document.save
    respond_to do |format|
      format.json {
        render json: {"url" => pan_url()}
      }
    end
  end

  # POST /kyc_documents/1/pan
  def null_cheque
    @kyc_document.null_cheque = params[:key]
    @kyc_document.save
    respond_to do |format|
      format.json {
        render json: {"url" => null_cheque_url()}
      }
    end
  end

  # POST /kyc_documents/1/pan
  def incorporation_cert
    @kyc_document.incorporation_cert = params[:key]
    @kyc_document.save
    respond_to do |format|
      format.json {
        render json: {"url" => incorporation_cert_url()}
      }
    end
  end

  def phonenumber
    @kyc_document.phonenumber = params[:key]
    @kyc_document.save
    respond_to do |format|
      format.json {
        render json: {"phonenumber" => @kyc_document.phonenumber}
      }
    end
  end

  def approval
    if current_user.is_super_admin? 
      @kyc_document.status = "APPROVED"
      @kyc_document.rejection_reason = nil
      @kyc_document.approved_by_id = current_user.id
      @kyc_document.approved_on = Time.now
      @kyc_document.save
      owner = User.find(@kyc_document.user_id)
      owner.kyc_approved = true
      owner.save
      return redirect_to kyc_documents_path
    end

    if current_user.role == 'user'
      if current_user.id != @kyc_document.user_id
        render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
        return
      end

      if !validate_kyc_information(@kyc_document)
        flash[:alert] = @errors
      else  
        @kyc_document.status = "SUBMITTED"
        @kyc_document.save
      end  
      return redirect_to new_kyc_document_path
    elsif current_user.role = 'ops'
      @kyc_document.status = "APPROVED"
      @kyc_document.rejection_reason = nil
      @kyc_document.approved_by_id = current_user.id
      @kyc_document.approved_on = Time.now
      @kyc_document.save
      owner = User.find(@kyc_document.user_id)
      owner.kyc_approved = true
      owner.save
      return redirect_to kyc_documents_path
    end
    render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
  end

  def reject
    if current_user.role == 'ops'
      @notice = "done"
      if params["message"].nil? or params["message"].empty?
        flash[:alert] = "Need a rejection reason."
        return redirect_to kyc_document_url(@kyc_document)
      end
      @kyc_document.rejection_reason = params[:message]
      @kyc_document.status = "REJECTED"
      @kyc_document.approved_by_id = nil
      @kyc_document.approved_on = nil
      @kyc_document.save
      return redirect_to kyc_documents_path
    end
    render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
  end
  # POST /kyc_documents
  # POST /kyc_documents.json
  def create
    @kyc_document = KycDocument.new(kyc_document_params)

    respond_to do |format|
      if @kyc_document.save
        format.html { redirect_to @kyc_document, notice: 'Kyc document was successfully created.' }
        format.json { render :show, status: :created, location: @kyc_document }
      else
        format.html { render :new }
        format.json { render json: @kyc_document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kyc_documents/1
  # PATCH/PUT /kyc_documents/1.json
  def update
    #validate_kyc_information(kyc_document_params)
    respond_to do |format|
      if @kyc_document.update(kyc_document_params)
        format.json { render :new, status: :ok, location: @kyc_document }
      else
        format.json { render json: @kyc_document.errors, status: :unprocessable_entity }
      end
    end
  end

  def validate_kyc_name(name)
    if name.present?
      name.strip.length > 0
    else
      false
    end  
  end

  def validate_kyc_company_address(company_address)
    if company_address.present?
      company_address.strip.length > 0
    else
      false
    end  
  end

  def validate_kyc_official_email(official_email)
    if official_email.present?
      @valid_email.match(official_email) != nil
    else
      false
    end  
  end

  def validate_kyc_company_name(company_name)
    if company_name.present?
      company_name.strip.length > 0
    else
      false
    end  
  end

  def validate_kyc_phonenumber(phonenumber)
    if phonenumber.present?
      phonenumber.strip.length > 0 and /^[0-9+]+$/.match(phonenumber.strip)
    else
      false
    end  
  end

  def validate_kyc_information(values)
    @errors=""
    @errors << "Invalid name. Cannot be empty.\n" unless validate_kyc_name(values["name"])
    @errors << "Invalid company address. Cannot be empty.\n" unless validate_kyc_company_address(values["company_address"])
    @errors << "Invalid official email.\n" unless validate_kyc_official_email(values["official_email"])
    @errors << "Invalid company name." unless validate_kyc_company_name(values["company_name"])
    @errors << "Invalid phone number only numbers, '+' allowed" unless validate_kyc_phonenumber(values["phonenumber"])
    @errors << "Invalid GST Number" unless validate_kyc_company_name(values["gst_number"])
    @errors << "Invalid PAN Card Number." unless validate_kyc_company_name(values["kyc_pan_card_number"])
    @errors << "Invalid IEC Number." unless validate_kyc_company_name(values["iec_number"])
    @errors << "Invalid State." unless validate_kyc_company_name(values["state"])
    @errors.length == 0
  end

  def information
    respond_to do |format|
      format.json { 
        if !validate_kyc_information(kyc_document_params)
          return render json: { error: @errors, success: false}, status: :unprocessable_entity
        end
        kyc_params = kyc_document_params
        @kyc_document.name = kyc_params["name"].strip
        @kyc_document.company_address = kyc_params["company_address"].strip
        @kyc_document.official_email = kyc_params["official_email"].strip
        @kyc_document.company_name = kyc_params["company_name"].strip
        @kyc_document.phonenumber = kyc_params["phonenumber"].strip
        @kyc_document.state = kyc_params["state"].strip
        @kyc_document.gst_number = kyc_params["gst_number"].strip
        @kyc_document.kyc_pan_card_number = kyc_params["kyc_pan_card_number"].strip
        @kyc_document.iec_number = kyc_params["iec_number"].strip
        @kyc_document.save!
        return render json: { success: true }, status: :ok
      }
    end
  end

  # DELETE /kyc_documents/1
  # DELETE /kyc_documents/1.json
  def destroy
    @kyc_document.destroy
    respond_to do |format|
      format.html { redirect_to kyc_documents_url, notice: 'Kyc document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def oops_lock
      @kyc_document = KycDocument.find(params[:kyc_document_id])
      @kyc_document.locked_by_user_id = current_user[:id]
      @kyc_document.is_locked = true
      if @kyc_document.save
        flash[:alert] = "Kyc Document is Locked Successfully"
          return redirect_to kyc_documents_path
      end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kyc_document
      @kyc_document = KycDocument.find(params[:id])
    end

    def set_parent_kyc_document
      @kyc_document = KycDocument.find(params[:kyc_document_id])
    end

    # Only allow a list of trusted parameters through.
    def kyc_document_params
      params.permit(:pan_card, :null_cheque, 

app/helpers/kyc_documents_helper.rb
module KycDocumentsHelper
end

app/views/kyc_documents/_form.html.erb
<div id="wrapper">
<!-- Content Wrapper -->
<div id="content-wrapper" class="d-flex flex-column">
   <div class="content">
        <!-- Topbar -->
   <nav class="navbar navbar-expand navbar-light bg-custom topbar mb-4 static-top shadow">

     <!-- Sidebar Toggle (Topbar) -->
     <button id="sidebarToggleTop" class="btn btn-link d-md-none mr-3">
       <span class="material-icons">menu</span>
     </button>
   </nav>
   
   <!-- End of Topbar -->

   <div class="container-fluid">
   <div class="logo-wrap" style="margin-top: 10px;
    margin-left: 10px;">
   <% if @kyc_document.status == 'DRAFT' %>
       <h2>WelCome to ScripMarket</h2>
       <h5>Please fill the below to proceed.</h5>
   <% end %>
   <% if @kyc_document.status == 'SUBMITTED' %>
       <h2>Waiting for Approval</h2>
       <h5>Our client executive is verifying your Information</h5>
   <% end %>
   <% if @kyc_document.status == 'REJECTED' %>
       <h2>Please Resubmit Information</h2>
       <h5>We found some errors in your KYC documents. Please correct them and resubmit</h5>
       <span>Rejection Reason: <%= @kyc_document.rejection_reason %></span>
    <% end %>
   <hr></hr>
   </div>


     <h4 class="general-heading mb-3 mt-3" style="margin-top: 10px;
    margin-left: 10px;"> Information </h4>
     <% if @kyc_document.status != 'SUBMITTED' and @kyc_document.status != 'APPROVED' %>
     <p id="kyc-document-information-message" class="alert alert-info"></p>
     <div class="row">
         <%= form_with(url: kyc_document_path(@kyc_document), method: "post", :html => { :id=>"kyc-document-information-form",  :class => "form-group m-b-15 information-form col-12" }) do %>
         <ul class="col-12 kyc-sub">
           <li class="col-xl-6 col-md-12 mb-3 mt-3"><%= text_field_tag(:name, @kyc_document.name, :class => "input-group-text", :placeholder => "Name", :id => "kyc-document-information-name") %> </li>
           <li class="col-xl-6 col-md-12 mb-3"><%= text_field_tag(:name, @kyc_document.phonenumber, :class => "input-group-text", :placeholder => "Phone Number", :id => "kyc-document-information-phonenumber") %>           </li>
           <li class="col-xl-6 col-md-12 mb-3"><%= text_field_tag(:official_email, @kyc_document.official_email, :class => "input-group-text", :placeholder=> "Official Email",:id => "kyc-document-information-official-email") %></li>
           <li class="col-xl-6 col-md-12 mb-3"><%= text_field_tag(:company_name, @kyc_document.company_name, :class => "input-group-text", :placeholder=> "Company Name", :id => "kyc-document-information-company-name") %></li>
           <li class="col-xl-6 col-md-12 mb-3"><%= text_field_tag(:gst_number, @kyc_document.gst_number, :class => "input-group-text", :placeholder=> "GST Number",:id => "kyc-document-information-gst_number") %></li>
           <li class="col-xl-6 col-md-12 mb-3"><%= text_field_tag(:kyc_pan_card_number,@kyc_document.kyc_pan_card_number, :class => "input-group-text", :placeholder=> "PAN Card Number",:id => "kyc-document-information-kyc_pan_card_number") %></li>
           <li class="col-xl-6 col-md-12 mb-3"><%= text_field_tag(:iec_number,@kyc_document.iec_number, :class => "input-group-text", :placeholder=> "IEC Number",:id => "kyc-document-information-iec_number") %></li>
           <li class="col-xl-6 col-md-12 mb-3 mt-3"><%= text_field_tag(:state, @kyc_document.state, :class => "input-group-text", :placeholder => "State", :id => "kyc-document-information-state") %> </li>
           <li class="col-xl-6 col-md-12 mb-3"><%= text_area_tag(:company_address, @kyc_document.company_address.presence || "Company Address" , :class => "input-group-text", :id => "kyc-document-information-company-address") %></li>
           <li class="col-xl-12 col-md-12 mb-3"><button kyc_id="<%= @kyc_document.id %>" id="kyc-document-information-submit" class="btn btn-info m-t-5 my-link" style="background-color: #0062cc;">Submit Information As Draft</button> </li>
         </ul>
         <% end %>
     </div>

     <%= form_with(url: kyc_document_approval_path(@kyc_document), method: "post",data: { confirm: "Do you really want submit kyc?", :class => "m-b-15" }) do %>
         <%= submit_tag("Submit Application for Approval", :class => "btn btn-success col-xs-12 col-xl-6", :style=>"background-color: #0062cc;margin-left: 280px;width: 264px;margin-top: -121px;") %>
     <% end %> 
     <% else %>
     <hr>
      <table style="margin-left: 20px;">
        <tr>
          <th><strong>Name:</strong></th>
          <td><%= @kyc_document.company_name %></td>
        </tr>
        <tr>
          <th><strong>Official Email:</strong></th>
          <td><%= @kyc_document.official_email %></td>
        </tr>
        <tr>
          <th><strong>Phone Number:</strong></th>
          <td><%= @kyc_document.phonenumber %></td>
        </tr>
        <tr>
          <th><strong>Company Name:</strong></th>
          <td><%= @kyc_document.company_name %></td>
        </tr>

        <tr>
          <th>Company Address:</th>
          <td><%= @kyc_document.company_address %></td>
        </tr>
        <tr>
          <th>GST Number:</th>
          <td><%= @kyc_document.gst_number %></td>
        </tr>
        <tr>
          <th>PAN Number:</th>
          <td><%= @kyc_document.kyc_pan_card_number %></td>
        </tr>
        <tr>
          <th>IEC Number:</th>
          <td><%= @kyc_document.iec_number %></td>
        </tr>
        <tr>
          <th>State:</th>
          <td><%= @kyc_document.state %></td>
        </tr>
        
      </table>
     <% end %>
     <div id="kyc-document-view">
     <img id='kyc-document-view-image'/>
     </div>
     </div>
     </div>
   </div>
   </div>
</div>
</div>
  <style>
table, th, td {
  border: 2px solid black;
  border-collapse: collapse;
}
th, td {
  padding: 5px;
  text-align: left;
}
input[type="file"] {
padding-left: 0px
}

</style>

app/views/kyc_documents/edit.html.erb
<h1>Editing Kyc Document</h1>

<%= render 'form', kyc_document: @kyc_document %>

<%= link_to 'Show', @kyc_document %> |
<%= link_to 'Back', kyc_documents_path %>

app/views/kyc_documents/new.html.erb
<%= render 'form', kyc_document: @kyc_document %>

app/views/kyc_documents/oldform.html.erb
<h3>Status</h3>
<span class='m-l-15'><%= @kyc_document.status %></span>
<% if @kyc_document.status == 'REJECTED' %>
    <span class='m-l-30'><%= @kyc_document.rejection_reason %></span>
<% end %>
<hr/>
<h3>Uploaded Images</h3>
<p id="kyc-document-images-message" class="alert alert-info"></p>
<div class="flex-container">
    <div class="card kyc-document-div">
        <img class='card-img-top kyc-document-image rounded' id="pan-image" src="<%= @pan_url %>"/>
        <div class='card-body'>
            <h5 class="card-title">Pan Card</h5>
            <% if @kyc_document.status != 'SUBMITTED' and @kyc_document.status != 'APPROVED' %>
                <div class="form-group">
                <input id="pan-upload-file" type="file"/>
                <button class='btn btn-info' id='pan-upload' kyc_id="<%= @kyc_document.id %>">Upload</button>
                </div>
            <% end %>
        </div>
    </div>
    <div class="card kyc-document-div">
        <img class='card-img-top kyc-document-image rounded' id="null-cheque-image" src="<%= @null_cheque_url %>"/>
        <div class='card-body'>
            <h5 class="card-title">Photo of Anulled Cheque Leaf</h5>
            <% if @kyc_document.status != 'SUBMITTED' and @kyc_document.status != 'APPROVED' %>
                <div class="form-group">
                <input id="null-cheque-upload-file" type="file"/>
                <button class='btn btn-info' id='null-cheque-upload' kyc_id="<%= @kyc_document.id %>">Upload</button>
                </div>
            <% end %>
        </div>
    </div>
    <div class="card kyc-document-div">
        <img class='card-image-top kyc-document-image rounded' id="incorporation-cert-image" src="<%= @incorporation_cert_url %>"/>
        <div class='card-body'>
            <h5 class='card-title'>Incorporation Certificate Photo</h5>
            <% if @kyc_document.status != 'SUBMITTED' and @kyc_document.status != 'APPROVED' %>
                <div class="form-group">
                <input id="incorporation-cert-upload-file" type="file"/>
                <button class='btn btn-info' id='incorporation-cert-upload' kyc_id="<%= @kyc_document.id %>">Upload</button>
                </div>
            <% end %>
        </div>
    </div>
</div>
<hr/>
<h3>Information</h3>

<% if @kyc_document.status != 'SUBMITTED' and @kyc_document.status != 'APPROVED' %>
    <p id="kyc-document-information-message" class="alert alert-info"></p>
    <%= form_with(url: kyc_document_path(@kyc_document), method: "post", :html => { :id=>"kyc-document-information-form",  :class => "form-group m-b-15 information-form" }) do %>
        <%= label_tag(:name,"Name:") %>
        <%= text_field_tag(:name, @kyc_document.name, :class => "form-control", :id => "kyc-document-information-name") %>
        <%= label_tag(:phonenumber,"Phone Number:") %>
        <%= text_field_tag(:name, @kyc_document.phonenumber, :class => "form-control", :id => "kyc-document-information-phonenumber") %>
        <%= label_tag(:official_email,"Official Email:") %>
        <%= text_field_tag(:official_email, @kyc_document.official_email, :class => "form-control", :id => "kyc-document-information-official-email") %>
        <%= label_tag(:company_name,"Company Name:") %>
        <%= text_field_tag(:company_name, @kyc_document.company_name, :class => "form-control", :id => "kyc-document-information-company-name") %>
        <%= label_tag(:company_address, "Company Address:") %>
        <%= text_area_tag(:company_address, @kyc_document.company_address, :class => "form-control", :id => "kyc-document-information-company-address") %>
        <button kyc_id="<%= @kyc_document.id %>" id="kyc-document-information-submit" class="btn btn-info m-t-5">Submit Information</button>
    <% end %>

    <hr/>
    
    <h3>Actions</h3>
    <%= form_with(url: kyc_document_approval_path(@kyc_document), method: "post", :html => { :onsubmit => "return confirm('Do you really want submit kyc?');", :class => "m-b-15" }) do %>
        <%= submit_tag("Submit Application for Approval", :class => "btn btn-success") %>
    <% end %>
<% else %>
    <span><b>Name:</b> <%= @kyc_document.name %></span><br/>
    <span><b>Official Email:</b> <%= @kyc_document.official_email %></span><br/>
    <span><b>Phone Number:</b> <%= @kyc_document.phonenumber %></span><br/>
    <span><b>Company Name:</b> <%= @kyc_document.company_name %></span><br/>
    <span><b>Company Address:</b> <%= @kyc_document.company_address %></span><br/>
<% end %>
<div id="kyc-document-view">
    <img id='kyc-document-view-image'/>
</div>

app/views/kyc_documents/show.html.erb
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
 <h2 class="title" style="margin-left: -11px;">Verify KYC Documents</h2> 
</nav>
<div class="form-inline">
  <div class="form-group" style="margin-left: 23px">
    <h3>Status:
    <span class='m-l-15'><%= @kyc_document.status.capitalize %></span></h3>
  </div>
</div>    
<hr/>


<hr/>
<h3 style="margin-left: 19px;">Information</h3>
      <table style="margin-left: 20px;">
        <tr>
          <th><strong>Name:</strong></th>
          <td><%= @kyc_document.company_name %></td>
        </tr>
        <tr>
          <th><strong>Official Email:</strong></th>
          <td><%= @kyc_document.official_email %></td>
        </tr>
        <tr>
          <th><strong>Phone Number:</strong></th>
          <td><%= @kyc_document.phonenumber %></td>
        </tr>
        <tr>
          <th><strong>Company Name:</strong></th>
          <td><%= @kyc_document.company_name %></td>
        </tr>

        <tr>
          <th>Company Address:</th>
          <td><%= @kyc_document.company_address %></td>
        </tr>
        <tr>
          <th>GST Number:</th>
          <td><%= @kyc_document.gst_number %></td>
        </tr>
        <tr>
          <th>PAN Number:</th>
          <td><%= @kyc_document.kyc_pan_card_number %></td>
        </tr>
        <tr>
          <th>IEC Number:</th>
          <td><%= @kyc_document.iec_number %></td>
        </tr>
        <tr>
          <th>State:</th>
          <td><%= @kyc_document.state %></td>
        </tr>

      </table>

<hr/>
<% if @kyc_document.status == "SUBMITTED" %>
  <% if @kyc_document.is_locked == false || (@kyc_document.is_locked == true &&  current_user[:id] == @kyc_document.locked_by_user_id) %>
    <h3 style="margin-left: 22px;">Actions</h3>
    <div class="kyc-document-div">
        <div class="button-div">
            <%= form_with(url: kyc_document_approval_path(@kyc_document), method: "post", :html => { :onsubmit => "return confirm('Do you really want approve kyc?');" } ) do %>
                <%= submit_tag("Approve", :class => "btn btn-success") %>
            <% end %>
        </div>

        <div class="button-div button-reject-div">
            <%= form_with(url: kyc_document_reject_path(@kyc_document), method: "post", :html => { :onsubmit => "return confirm('Do you really want reject kyc?');" } ) do %>
                <%= text_area_tag :message, nil, placeholder: "Rejection Reason" %>
                <%= submit_tag("Reject", :class => "btn btn-danger") %>
            <% end %>
        </form>
        </div>
        <% if @kyc_document.is_locked != true %>
          <div class="button-div ">
              <%= form_with(url: kyc_document_oops_lock_path(@kyc_document), method: "get", :html => { :onsubmit => "return confirm('Do you really want Lock kyc?');" } ) do %>
                  <%= submit_tag("Lock", :class => "btn btn-danger",:style => "background-color: black" ) %>
              <% end %>
          </form>
          </div>
        <% end %>  
    </div>
    <div id="kyc-document-view">
        <img id='kyc-document-view-image'/>
    </div>
  <% end %>  
<% end %>  
<style>
  table, th, td {
    border: 2px solid black;
    border-collapse: collapse;
  }
  th, td {
    padding: 5px;
    text-align: left;
  }
</style>