config/routes.rb
Rails.application.routes.draw do
  resources :buy_requests do
    post 'submit', action: :submit
    post 'is_sold', action: :is_sold
    get 'lock_buy', action: :lock_buy
    post 'audit', action: :audit



    post 'audit_reject', action: :audit_reject
    get 'reject_buy', action: :reject_buy
  end
  resources :sell_requests do
    post 'resubmit', action: :resubmit
    post 'upload_invoice', action: :upload_invoice
  end
  get 'dashboard/home', action: :home, controller: 'dashboard'
  get 'dashboard/sell', action: :sell, controller: 'dashboard'
  get 'dashboard/buy', action: :buy, controller: 'dashboard'
  get 'dashboard/business_config', action: :business_config, controller: 'dashboard'
  get 'dashboard/select_scrips_user', action: :select_scrips_user, controller: 'dashboard'
  get 'dashboard/select_scrips_ops', action: :select_scrips_ops, controller: 'dashboard'

  get 'dashboard/download_pdf', action: :download_pdf, controller: 'dashboard'


  get 'dashboard/verify_buy', action: :verify_buy, controller: 'dashboard'
  get 'dashboard/audit_dashboard', action: :audit_dashboard, controller: 'dashboard'
  get 'dashboard/procees_to_sell', action: :procees_to_sell, controller: 'dashboard'


  resources :permissions, only: [:index, :edit, :update]

  resources :buy_sell_binding, only: [:create, :destroy]

  get 'verify_sell_rejections', action: :rejections, controller: 'verify_sell'

  resources :verify_sell, only: [:index, :show] do
    post 'verify', action: :verify
    post 'reject', action: :reject
    get 'request_lock', action: :request_lock

  end
  get 'dashboard/invoices', action: :invoices, controller: 'dashboard'

  get 'dashboard/buy_request_audit', action: :buy_request_audit, controller: 'dashboard'

  resources :kyc_documents do
    post 'pan', action: :pan
    post 'null_cheque', action: :null_cheque
    post 'incorporation_cert', action: :incorporation_cert
    post 'phonenumber', action: :phonenumber
    post 'approval', action: :approval
    post 'reject', action: :reject
    post 'information', action: :information
    get 'oops_lock', action: :oops_lock
  end
  resources :s3url, only: [:index]
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", confirmations: 'confirmations' }
  root to: "home#index"
  get 'kyc', action: :show, controller: 'kyc', as: 'kyc'
  get 'logout', action: :logout, controller: 'application', as: 'logout'
  resources :business_configs, only: [ :update ]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :kyc_documents, :class_name => 'KycDocument', :foreign_key => 'user_id'
  has_many :approved_kyc_documents, :class_name => 'KycDocument', :foreign_key => 'approved_by_id'
  has_one :user_attributes, :class_name => 'UserAttribute', :foreign_key => 'user_id'
  has_many :sell_requests, :class_name => 'SellRequest', :foreign_key => 'verified_by'
  
  def can?(permission)
    self.user_attributes.can?(permission)
  end

  def is_super_admin?
    ["pramodbha8@gmail.com"].split(',').flatten.include?(self.email)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

    protected
    def after_sign_up_path_for(resource)
        # return the path based on resource
        new_user_session_path
    end

    def after_inactive_sign_up_path_for(resource)
        new_user_session_path
    end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users/sessions_helper.rb
module Users::SessionsHelper
end

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <li class="txt-link">
    <%= link_to "Log in", new_session_path(resource_name) %>
  </li>
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <li class="txt-link">
    <%= link_to "Sign up", new_registration_path(resource_name) %>
  </li>
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
<li class="txt-link">
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
</li>
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
<li class="txt-link">
  <%= link_to "Didn't receive confirmation instructions?", new_user_confirmation_path(resource_name) %><br />
</li>
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
<li class="txt-link">
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
</li>
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <li class="txt-link">
      <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
    </li>
  <% end %>
<% end %>