config/routes.rb
Rails.application.routes.draw do
  resources :buy_requests do
    post 'submit', action: :submit
    post 'is_sold', action: :is_sold
    get 'lock_buy', action: :lock_buy
    post 'audit', action: :audit



    post 'audit_reject', action: :audit_reject
    get 'reject_buy', action: :reject_buy
  end
  resources :sell_requests do
    post 'resubmit', action: :resubmit
    post 'upload_invoice', action: :upload_invoice
  end
  get 'dashboard/home', action: :home, controller: 'dashboard'
  get 'dashboard/sell', action: :sell, controller: 'dashboard'
  get 'dashboard/buy', action: :buy, controller: 'dashboard'
  get 'dashboard/business_config', action: :business_config, controller: 'dashboard'
  get 'dashboard/select_scrips_user', action: :select_scrips_user, controller: 'dashboard'
  get 'dashboard/select_scrips_ops', action: :select_scrips_ops, controller: 'dashboard'

  get 'dashboard/download_pdf', action: :download_pdf, controller: 'dashboard'


  get 'dashboard/verify_buy', action: :verify_buy, controller: 'dashboard'
  get 'dashboard/audit_dashboard', action: :audit_dashboard, controller: 'dashboard'
  get 'dashboard/procees_to_sell', action: :procees_to_sell, controller: 'dashboard'


  resources :permissions, only: [:index, :edit, :update]

  resources :buy_sell_binding, only: [:create, :destroy]

  get 'verify_sell_rejections', action: :rejections, controller: 'verify_sell'

  resources :verify_sell, only: [:index, :show] do
    post 'verify', action: :verify
    post 'reject', action: :reject
    get 'request_lock', action: :request_lock

  end
  get 'dashboard/invoices', action: :invoices, controller: 'dashboard'

  get 'dashboard/buy_request_audit', action: :buy_request_audit, controller: 'dashboard'

  resources :kyc_documents do
    post 'pan', action: :pan
    post 'null_cheque', action: :null_cheque
    post 'incorporation_cert', action: :incorporation_cert
    post 'phonenumber', action: :phonenumber
    post 'approval', action: :approval
    post 'reject', action: :reject
    post 'information', action: :information
    get 'oops_lock', action: :oops_lock
  end
  resources :s3url, only: [:index]
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", confirmations: 'confirmations' }
  root to: "home#index"
  get 'kyc', action: :show, controller: 'kyc', as: 'kyc'
  get 'logout', action: :logout, controller: 'application', as: 'logout'
  resources :business_configs, only: [ :update ]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <title>Scripmarket</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

        <meta charset="UTF-8">
        <meta name="keywords" content="Scrip, Export, Business">
        <meta name="description" content="Exchange Scrip for export business.">
        <meta name="viewport" content="width=device-width, initial-scale=1">
      <!--===============================================================================================-->    
        <link rel="icon" type="image/png" href="/images/icons/favicon.ico"/>
      <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="/vendor/bootstrap/css/bootstrap.min.css">
      <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
      <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="/fonts/iconic/css/material-design-iconic-font.min.css">
      <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="/vendor/animate/animate.css">
      <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="/vendor/select2/select2.min.css">
      <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="/css/util.css">
        <link rel="stylesheet" type="text/css" href="/css/main.css">
        <link href="/css/sb-admin-2.css" rel="stylesheet">
        <link href="/css/all.min.css" rel="stylesheet" type="text/css">
      <!--===============================================================================================-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons"  rel="stylesheet">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
          <script type="text/javascript" charset="utf8" src="/js/jquery-3.5.1.min.js"></script>
          <script type="text/javascript" charset="utf8" src="/js/jquery.dataTables.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="/css/font-awesome.min.css">
        <script src="/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="/css/font-awesome.min.css">
        <link rel="stylesheet" type="text/css" href="/css/jquery.dataTables.css">

      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="page-top">
  <div id="wrapper">
    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
    <!-- Sidebar - Brand -->
        <li>
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="<%= dashboard_home_path %>">
                <div class="sidebar-brand-icon">
                    <img src="/images/logo-icon.png"  alt="ScripMarket">
                </div>
                <div class="sidebar-brand-text mx-3"><img src="/images/logo-sm.png"  alt="ScripMarket"></div>
            </a>
        </li>

    <% if !@hide_side_bar %>
    <!-- Nav Item - Dashboard -->
        <li class="nav-item <%= active_class?(dashboard_home_path) %>">
            <a class="nav-link" href="<%= dashboard_home_path %>">
                <span class="material-icons <%= @dashboard_visible %> <%= @dashboard_selected %>" style="color:#AFAB37;">home</span>
                <span class="tab-label">Dashboard</span>
            </a>
        </li>

    <% if @user.can?("sell") %>
    <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item <%= active_class?(new_sell_request_path) %>">
            <a class="nav-link collapsed" href="<%= new_sell_request_path %>" >
                <span class="material-icons" style="color:#25A707;">arrow_circle_down</span>
                <span class="tab-label">Place Sell Request</span>
            </a> 
        </li>
    <% end %>

    <% if @user.can?("buy") %>
    <!-- Nav Item - Utilities Collapse Menu -->
        <li class="nav-item <%= active_class?(new_buy_request_path) %>">
            <a class="nav-link collapsed" href="<%= new_buy_request_path %>">
                <span class="material-icons" style="color:#25A707; transform: scaleY(-1);">arrow_circle_down</span>
                <span class="tab-label">Place Buy Request</span>
            </a>  
        </li>
    <% end %>

    <% if @user.can?("sell") %>
    <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item <%= active_class?(dashboard_sell_path) %>">
            <a class="nav-link collapsed" href="<%= dashboard_sell_path %>" >
                <span class="material-icons" style="color:#49BCE1;">exit_to_app</span>
                <span class="tab-label">Sell</span>
            </a>
        </li>
    <% end %>


    <% if @user.can?("buy") %>
    <!-- Nav Item - Charts -->
        <li class="nav-item <%= active_class?(dashboard_buy_path) %>">
            <a class="nav-link" href="<%= dashboard_buy_path %>">
                <span class="material-icons" style="color:#E97575; transform:scaleX(-1);">exit_to_app</span>
                <span class="tab-label">Buy</span>
            </a>
        </li>
    <% end %>

    <% if @user.can?("verify_scrip")  %>
    <!-- Nav Item - Tables -->
        <li class="nav-item <%= active_class?(verify_sell_index_path) %>">
            <a class="nav-link" href="<%= verify_sell_index_path %>">
                <span class="material-icons" style="color:#89E9B6;">verified</span>
                <span class="tab-label">Verify Sell Request</span>
            </a>
        </li>
    <% end %>

    <% if @user.can?("verify_kyc")  %>
    <!-- Nav Item - Tables -->
        <li class="nav-item <%= active_class?(kyc_documents_path) %>">
            <a class="nav-link" href="<%= kyc_documents_path %>">
                <span class="material-icons" style="color:#89E9B6;">verified_user</span>
                <span class="tab-label">Verify KYC</span>
            </a>
        </li>
    <% end %>

    <% if @user.user_attributes.preferences["audit"] == true%>
    <!-- Nav Item - Tables -->
        <li class="nav-item <%= active_class?(dashboard_audit_dashboard_path) %>">
            <a class="nav-link" href="<%= dashboard_audit_dashboard_path %>">
                <span class="material-icons" style="color:blue;">check_circle</span>
                <span class="tab-label">Audits</span>
            </a>
        </li>
    <% end %>
<!-- 
    <li class="nav-item <%= active_class?(dashboard_procees_to_sell_path) %>">
        <a class="nav-link" href="<%= dashboard_procees_to_sell_path %>">
            <span class="material-icons" style="color:green;">info</span>
            <span class="tab-label">Process</span>
        </a>
    </li> -->


    <% if @user.can?("verify_buy")%>
    <!-- Nav Item - Tables -->
    <li class="nav-item <%= active_class?(dashboard_verify_buy_path) %>">
        <a class="nav-link" href="<%= dashboard_verify_buy_path %>">
            <span class="material-icons" style="color:#89E9B6;">published_with_changes</span>
            <span class="tab-label">Verify Buy</span>
        </a>
    </li>
    <% end %>

        <% if @user.is_super_admin? || @user.role == "ops" %>
        <!-- Nav Item - Tables -->
            <li class="nav-item <%= active_class?(dashboard_business_config_path) %>">
                <a class="nav-link" href="<%= dashboard_business_config_path %>">
                    <span class="material-icons" style="color:#89E9B6;">business_center</span>
                    <span class="tab-label">Business Config</span>
                </a>
            </li>
        <% end %>
        <% if @user.is_super_admin? || @user.role == "ops"  %>
        <!-- Nav Item - Tables -->
        <li class="nav-item <%= active_class?(permissions_path) %>">
            <a class="nav-link" href="<%= permissions_path %>">
                <span class="material-icons" style="color:#89E9B6;">perm_identity</span>
                <span class="tab-label">User Admin</span>
            </a>
        </li>
        <% end %>
<!--         <li class="nav-item <%= active_class?(logout_path) %>">
            <a class="nav-link" href="<%= dashboard_invoices_path %>">
                <span class="material-icons" style="color:#FE4545;">list_alt</span>
                <span class="tab-label">Invoice</span>
            </a>
        </li>
 -->    <% end %>
        <li class="nav-item <%= active_class?(logout_path) %>">
            <a class="nav-link" href="<%= logout_path %>">
                <span class="material-icons" style="color:#A85ED8;">power_settings_new</span>
                <span class="tab-label">Logout</span>
            </a>
        </li>
  </ul>
  <!-- End of Sidebar -->
  <!-- Content Wrapper -->
  <div id="content-wrapper" class="d-flex flex-column">
      <div class="content">
        <div class="dis-inline-block w-screen">
        <% if notice %>
            <p class="alert alert-info"><%= notice %></p>
        <% end %>
        <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
        <% end %>
        <div>
        <%= yield %>
      </div>
  </div>
  </div>
  <a class="scroll-to-top rounded" href="#page-top">
  <i class="fas fa-angle-up"></i>
</a>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
      <title>Scripmarket</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

        <meta charset="UTF-8">
        <meta name="keywords" content="Scrip, Export, Business">
        <meta name="description" content="Exchange Scrip for export business.">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
      <!--===============================================================================================-->	
	    <link rel="icon" type="image/png" href="/images/icons/favicon.ico"/>
      <!--===============================================================================================-->
	    <link rel="stylesheet" type="text/css" href="/vendor/bootstrap/css/bootstrap.min.css">
      <!--===============================================================================================-->
	    <link rel="stylesheet" type="text/css" href="/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
      <!--===============================================================================================-->
	    <link rel="stylesheet" type="text/css" href="/fonts/iconic/css/material-design-iconic-font.min.css">
      <!--===============================================================================================-->
	    <link rel="stylesheet" type="text/css" href="/vendor/animate/animate.css">
      <!--===============================================================================================-->
	    <link rel="stylesheet" type="text/css" href="/vendor/select2/select2.min.css">
      <!--===============================================================================================-->
	    <link rel="stylesheet" type="text/css" href="/css/util.css">
	    <link rel="stylesheet" type="text/css" href="/css/main.css">
      <!--==========================================================================================-->
      <link href="/css/style.css" rel="stylesheet" type="text/css" media="all">
      <link href="/css/demo.css" rel="stylesheet" type="text/css" media="all">
      <link href="/css/responsive.css" rel="stylesheet" type="text/css" media="all">
      <!--===============================================================================================-->      
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="page-body">
    <div class="page-wrap">
      <header class="page-header">
        <div class="logo-wrap">
          <a href="/index.html"> <img src="/images/logo-sm.png"  alt="ScripMarket"></a>
        </div>
        <nav class="menu-wide">
          <ul class="main-menu">
          </ul>
        </nav>
        <nav class="menu" >
          <ul class="active" >
          </ul>
          <a class="toggle-nav" href="http://demos.inspirationalpixels.com/responsive-menu/#">_</a>
        </nav>
      </header>
      <section>
        <div class="dis-inline-block w-screen">
          <% if notice %>
            <p class="alert alert-info"><%= notice %></p>
          <% end %>
          <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
          <% end %>
          <div>
            <%= yield %>
          </div>
        </div>
      </section>
      <footer>
        <div class="footer-in">
        <p> Scrip Exchange, Simplified!!</p>
        </div>
      </footer>
    </body>
  </div>
</html>